version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  node_build_test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:15.1
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps

    working_directory: ~/app # directory where steps will run

    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
            - node-deps-v1-
      - run:
          name: install packages
          working_directory: ~/app
          command: npm install
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
            - node_modules
            - ~/.cache
      - run:
          name: Run Tests
          working_directory: ~/app
          command: npm run test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - node_build_test
      - heroku/deploy-via-git:
          requires:
            - node_build_test
          filters:
            branches:
              only: main
